create table if not exists public.rise_user (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  organization_id text not null,
  can_create boolean not null default false,
  can_read boolean not null default false,
  can_update boolean not null default false,
  can_delete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists rise_user_user_id_idx on public.rise_user(user_id);
create index if not exists rise_user_organization_id_idx on public.rise_user(organization_id);

create or replace function public.set_rise_user_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_rise_user_updated_at on public.rise_user;

create trigger set_rise_user_updated_at
before update on public.rise_user
for each row
execute function public.set_rise_user_updated_at();
