export interface School {
  id: string
  created_at?: string
  org?: string
  sch_code?: string
  sch_name_eng?: string
  sch_name_bur?: string
  sch_name_loc?: string
  pcode_sr_mimu?: string
  sr_eng_mimu?: string
  sr_bur_mimu?: string
  pcode_dist_mimu?: string
  dist_eng_mimu?: string
  dist_bur_mimu?: string
  pcode_ts_mimu?: string
  ts_eng_mimu?: string
  ts_bur_mimu?: string
  ts_loc?: string
  pcode_vt_mimu?: string
  vt_eng_mimu?: string
  vt_bur_mimu?: string
  vt_loc?: string
  pcode_vil_mimu?: string
  vil_eng?: string
  vil_bur?: string
  vil_loc?: string
  sch_status?: string
  sch_estd_year?: number
  sch_type?: string
  cur?: string
  grade_system?: string
  sch_com?: number
  sch_com_f?: number
  sch_com_tt?: number
  sch_pta?: number
  sch_pta_f?: number
  sch_pta_m?: number
  std_dorm?: string
  main_lang_in?: string
  enroll_fee?: number
  n_fee?: number
  p_fee?: number
  m_fee?: number
  h_fee?: number
  tea_female_moe?: number
  tea_male_moe?: number
  tea_female_com?: number
  tea_male_com?: number
  tees_female?: number
  tees_male?: number
  tea_moe_com_f?: number
  tea_moe_com_m?: number
  tea_moe_com_tt?: number
  stu_female_tt?: number
  stu_male_tt?: number
  nur_female?: number
  nur_male?: number
  low_pri_female?: number
  low_pri_male?: number
  low_pri_tt?: number
  up_pri_female?: number
  up_pri_male?: number
  mid_female?: number
  mid_male?: number
  high_female?: number
  high_male?: number
  n_female?: number
  n_male?: number
  kg_female?: number
  kg_male?: number
  g1_female?: number
  g1_male?: number
  g2_female?: number
  g2_male?: number
  g3_female?: number
  g3_male?: number
  g4_female?: number
  g4_male?: number
  g5_female?: number
  g5_male?: number
  g6_female?: number
  g6_male?: number
  g7_female?: number
  g7_male?: number
  g8_female?: number
  g8_male?: number
  g9_female?: number
  g9_male?: number
  g10_female?: number
  g10_male?: number
  g11_female?: number
  g11_male?: number
  g12_female?: number
  g12_male?: number
  sch_build_bb?: boolean
  sch_build_wd?: boolean
  sch_build_bk_cmt?: boolean
  sch_build_oth?: boolean
  sch_facil_nn?: boolean
  sch_facil_pg?: boolean
  sch_facil_lby?: boolean
  sch_facil_off?: boolean
  sch_facil_dw?: boolean
  sch_facil_fc?: boolean
  sch_facil_hk?: boolean
  sch_facil_tl?: boolean
  sch_facil_oth?: boolean
  sch_resou_nn?: boolean
  sch_resou_com?: boolean
  sch_resou_cam?: boolean
  sch_resou_sol?: boolean
  sch_resou_pho?: boolean
  sch_resou_hyd?: boolean
  sch_resou_tye?: boolean
  sch_resou_gen?: boolean
  sch_resou_pri?: boolean
  sch_resou_oth?: boolean
  sch_com_nn?: boolean
  sch_com_ph?: boolean
  sch_com_tel?: boolean
  sch_com_let?: boolean
  sch_com_wktk?: boolean
  sch_com_int?: boolean
  sch_com_oth?: boolean
  class_sun_light?: string
  class_wind_vent?: string
  has_sch_fence?: boolean
  water_source_nn?: boolean
  water_source_well?: boolean
  water_source_stream?: boolean
  water_source_river?: boolean
  water_source_rain?: boolean
  water_source_oth?: boolean
  sch_flag?: boolean
  signboard?: boolean
  sch_location_type?: string
  out_tea_stipend?: boolean
  out_who_support?: string
  out_sch_fin?: boolean
  fin_who_support?: string
  out_mat_support?: boolean
  out_mat_items?: string
  mat_who_support?: string
  com_tea_stipend?: boolean
  com_food?: boolean
  com_food_nn?: boolean
  com_food_ric?: boolean
  com_food_veg?: boolean
  com_food_oil?: boolean
  com_food_sal?: boolean
  com_food_mea?: boolean
  com_food_fis?: boolean
  com_food_chi?: boolean
  com_food_oth?: boolean
  com_sch_fin?: boolean
  com_mat_support?: boolean
  com_mat_items?: string
  moe_tea_stipend?: boolean
  moe_mat_support?: boolean
  moe_mat_items?: string
  vil_admin_level?: string
  vil_transportation?: string
  vil_livelihood?: string
  vil_household?: number
  no_nur_sch?: number
  no_pri_sch?: number
  no_up_pri_sch?: number
  no_mid_sch?: number
  no_hig_sch?: number
  no_post12_sch?: number
  boys_oosc_5_18?: number
  girls_oosc_5_18?: number
  sch_boys_5_18?: number
  sch_girls_5_18?: number
  boys_orphan_5_18?: number
  girls_orphan_5_18?: number
  boys_disability_5_18?: number
  girls_disability_5_18?: number
  vil_grad?: string
  religion_in_vil?: string
  vil_ethnic?: string
  vil_main_lang?: string
  vil_oth_lang?: string
  joined_rise?: boolean
  nfe?: boolean
}
